.TH "src Directory Reference" 3 "Fri Apr 1 2022" "Version Alpha" "M1_Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInstruction_Process_Methods\&.c\fP"
.br
.RI "Contains function definitions for processing the instructions\&. "
.ti -1c
.RI "file \fBInstruction_to_Hex\&.c\fP"
.br
.RI "Contains function definitions required to convert an Instruction to the equivalent Hex Code\&. "
.ti -1c
.RI "file \fBProject_main\&.c\fP"
.br
.RI "Main file of the project\&. "
.in -1c
