.TH "src/Project_main.c" 3 "Fri Apr 1 2022" "Version Alpha" "M1_Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Project_main.c \- Main file of the project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Instruction_Process_Methods\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAssembly_Code_Path\fP   '\&./test/test_code\&.asm'"
.br
.ti -1c
.RI "#define \fBHex_File_Output_Path\fP   '\&./output/hex_file\&.hex'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main file of the project\&. 


.PP
\fBAuthor\fP
.RS 4
Sanjeeve R (18euee122@skcet.ac.in) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-03-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define Assembly_Code_Path   '\&./test/test_code\&.asm'"

.SS "#define Hex_File_Output_Path   '\&./output/hex_file\&.hex'"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for M1_Assembler from the source code\&.
