name: Valgrind

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind and Run Memory Check
      run: |
        sudo apt-get install valgrind
        make memcheck -C ./3_Implementation
